# Generated by Django 4.1.1 on 2023-01-13 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('notas', models.TextField()),
            ],
        ),
    ]
